name: kulinerku
description: A Flutter application for culinary management with Appwrite backend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Appwrite SDK
  appwrite: ^12.0.3
  
  # Image handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # Location services
#  geolocator: ^10.1.0
  location: ^5.0.3
  geocoding: ^2.1.1 
  permission_handler: ^11.1.0
  
  flutter_local_notifications: ^17.1.2

  connectivity_plus: ^5.0.2  # Untuk memantau koneksi internet
  
  # UI Components
  flutter_rating_bar: ^4.0.1
  
  # Utilities
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
#  assets:
#    - assets/images/
dependency_overrides:
  flutter_web_auth_2: ^3.1.2